version: 2

references:
  defaults: &defaults
    working_directory: ~/react-component-from-prop
  nodejs: &nodejs
    <<: *defaults
    docker:
      - image: circleci/node:10.15.3
  restore_npm_cache: &restore_npm_cache
    name: Restoring Cache - npm
    keys:
      - npm-v1-{{ checksum "package-lock.json" }}
      - npm-v1-
  save_npm_cache: &save_npm_cache
    key: npm-v1-{{ checksum "package-lock.json" }}
    paths:
      - ./node_modules

jobs:
  test:
    <<: *nodejs
    steps:
      - checkout
      - restore_cache: *restore_npm_cache
      - run: npm install
      - save_cache: *save_npm_cache
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Tests
          command: npm run test:coverage
      - run:
          name: Upload Coverage Report
          command: npm run coverage-report-upload

  build:
    <<: *nodejs
    steps:
      - checkout
      - restore_cache: *restore_npm_cache
      - run: npm install
      - save_cache: *save_npm_cache
      - run:
          name: Build assets
          command: NODE_ENV=production npm run compile
      - persist_to_workspace:
          root: lib
          paths: .
  
  publish:
    <<: *nodejs
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-component-from-prop/lib
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ~/.npmrc
      - run:
          name: Publish package to npm and tagging
          command: /bin/bash .circleci/publish-and-tagging.sh

workflows:
  version: 2
  test_build_publish:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
